[build]
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.filter(username='romaric').exists() or User.objects.create_superuser('romaric', 'romaricyelkouni1@gmail.com', 'unzmpci2025')\""

[deploy]
startCommand = "gunicorn config.wsgi:application"
